// Generated by gencpp from file tku_msgs/detector.msg
// DO NOT EDIT!


#ifndef STRATEGY_MESSAGE_DETECTOR_H
#define STRATEGY_MESSAGE_DETECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

namespace strategy
{
template <class ContainerAllocator>
struct detector_
{
  typedef detector_<ContainerAllocator> Type;

  detector_()
    : x(0)
    , y(0)
    , height(0)
    , width(0)  
    , arrow(0)  {
    }
  detector_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , height(0)
    , width(0)  
    , arrow(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;

  typedef int32_t _arrow_type;
  _arrow_type arrow;





  typedef boost::shared_ptr< ::strategy::detector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::strategy::detector_<ContainerAllocator> const> ConstPtr;

}; // struct detector_

typedef ::strategy::detector_<std::allocator<void> > detector;

typedef boost::shared_ptr< ::strategy::detector > detectorPtr;
typedef boost::shared_ptr< ::strategy::detector const> detectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::strategy::detector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::strategy::detector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tku_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tku_msgs': ['/home/alexis/Desktop/MAR/src/tku_msgs/msg/vision', '/home/alexis/Desktop/MAR/src/tku_msgs/msg/motionpackage', '/home/alexis/Desktop/MAR/src/tku_msgs/msg/usb_cam', '/home/alexis/Desktop/MAR/src/tku_msgs/msg/walkinggait', '/home/alexis/Desktop/MAR/src/tku_msgs/msg/Localization', '/home/alexis/Desktop/MAR/src/tku_msgs/msg/Ros2MultiCommunication'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::strategy::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::strategy::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::strategy::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::strategy::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::strategy::detector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::strategy::detector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::strategy::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77cbce8086047f00755fff9fa950d785";
  }

  static const char* value(const ::strategy::detector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77cbce8086047f00ULL;
  static const uint64_t static_value2 = 0x755fff9fa950d785ULL;
};

template<class ContainerAllocator>
struct DataType< ::strategy::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "strategy/detector";
  }

  static const char* value(const ::strategy::detector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::strategy::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 height\n\
int32 width\n\
int32 arrow\n\
";
  }

  static const char* value(const ::strategy::detector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::strategy::detector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.arrow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::strategy::detector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::strategy::detector_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "arrow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.arrow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_DETECTOR_H
